= Cahier De Recette du site web REVIVE
:toc:
:toc-title: Sommaire



== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre de la conception d'un site web pour l'entreprise REVIVE. Ce document spécifie l'ensemble des cas testés pour ce dernier.



== II. Pre-Requis :
[.text-justify]
L'exécution des tests requiert :

* L'accès au http://193.54.227.164/~SAESYS07/pages/[site web REVIVE]


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les User-Stories spécifiées dans le *CDCF* donné dans l'appel d'offre de REVIVE.


=== 2. Environnement de test :
[.text-justify]
Un navigateur web quelconque.



== III. Cas de test :
=== 1. Connexion et données de compte :
==== 1.1 Connexion :

|====

>|Cas de test 3+|Test-01-01-01
>|Titre 3+|Connexion en tant que client
>|Objectif 3+| Vérifier qu'il est possible de se connecter en tant que client sur la page connexion.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Saisir une mauvaise adresse mail  ^|Affichage d'un message d'erreur ^|OK
^|2 ^|Saisir un mauvais mot de passe ^|Affichage d'un message d'erreur ^|OK
^|3 ^|Saisir des données de client correctes ^|Connexion en tant que client et redirection vers la page d'accueil ^|OK

|====

|====

>|Cas de test 3+|Test-01-01-02
>|Titre 3+|Connexion en tant qu'administrateur
>|Objectif 3+| Vérifier qu'il est possible de se connecter en tant qu'administrateur sur la page connexion.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Saisir une mauvaise adresse mail  ^|Affichage d'un message d'erreur ^|OK
^|2 ^|Saisir un mauvais mot de passe ^|Affichage d'un message d'erreur ^|OK
^|3 ^|Saisir des données d'administrateur correctes ^|Connexion en tant qu'administrateur et redirection vers la page d'accueil ^|OK

|====


==== 1.2 Création d'un compte :

|====

>|Cas de test 3+|Test-01-02-01
>|Titre 3+|Création d'un compte client
>|Objectif 3+| Vérifier qu'il est possible de créer un compte client sur la page creationCompte.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Saisir une mauvaise adresse mail  ^|Affichage d'un message d'erreur ^|OK
^|2 ^|Saisir un mauvais mot de passe ^|Affichage d'un message d'erreur ^|OK
^|3 ^|Saisir des données de client correctes ^|Ajout des données dans la BD et redirection vers la page de connexion ^|OK

|====


==== 1.3 Consultation d'un compte :

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Page sécurisée
>|Objectif 3+| Vérifier que la page consultCompte.php n'est pas accessible si l'utilisateur n'est pas connecté

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Accéder à la page sans être connecté  ^|Redirection vers la page de connexion ^|OK
^|2 ^|Accéder à la page avec de mauvaises données de session ^|Redirection vers la page de connexion ^|OK
^|3 ^|Accéder à la page en étant connecté en tant que client ou administrateur ^|Accès à la page ^|OK

|====

|====

>|Cas de test 3+|Test-01-03-02
>|Titre 3+|Consultation d'un compte client
>|Objectif 3+| Vérifier qu'il est possible de consulter les données d'un compte client sur la page consultCompte.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Accéder à la page en étant connecté en tant que client ^|Accès à la page et affichage des données du compte client ^|OK

|====

|====

>|Cas de test 3+|Test-01-03-03
>|Titre 3+|Consultation d'un compte administrateur
>|Objectif 3+| Vérifier qu'il est possible de consulter les données d'un compte administrateur sur la page consultCompte.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Accéder à la page en étant connecté en tant qu'administrateur ^|Accès à la page et affichage des données du compte administrateur ^|OK

|====


==== 1.4 Modification d'un compte :

|====

>|Cas de test 3+|Test-01-04-01
>|Titre 3+|Page sécurisée
>|Objectif 3+| Vérifier que la page modifierCompte.php n'est pas accessible si l'utilisateur n'est pas connecté

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Accéder à la page sans être connecté  ^|Redirection vers la page de connexion ^|OK
^|2 ^|Accéder à la page avec de mauvaises données de session ^|Redirection vers la page de connexion ^|OK
^|3 ^|Accéder à la page en étant connecté en tant que client ou administrateur ^|Accès à la page ^|OK

|====

|====

>|Cas de test 3+|Test-01-04-02
>|Titre 3+|Modification d'un compte client
>|Objectif 3+| Vérifier qu'il est possible de modifier les données d'un compte client sur la page modifierCompte.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Saisir une mauvaise adresse mail ou une adresse déjà existante  ^|Affichage d'un message d'erreur ^|OK
^|2 ^|Saisir un mauvais nouveau mot de passe ^|Affichage d'un message d'erreur ^|OK
^|2 ^|Saisir un mauvais ancien mot de passe ^|Affichage d'un message d'erreur ^|OK
^|4 ^|Saisir des données de client correctes ^|Modification des données dans la BD ^|OK

|====

|====

>|Cas de test 3+|Test-01-04-03
>|Titre 3+|Modification d'un compte administrateur
>|Objectif 3+| Vérifier qu'il est possible de modifier les données d'un compte administrateur sur la page modifierCompte.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Saisir une mauvaise adresse mail ou une adresse déjà existante  ^|Affichage d'un message d'erreur ^|OK
^|2 ^|Saisir un mauvais nouveau mot de passe ^|Affichage d'un message d'erreur ^|OK
^|2 ^|Saisir un mauvais ancien mot de passe ^|Affichage d'un message d'erreur ^|OK
^|4 ^|Saisir des données de client correctes ^|Modification des données dans la BD ^|OK

|====

=== 2. Pages produits
==== 2.1 Consultation de produit :

|====

>|Cas de test 3+|Test-02-01-01
>|Titre 3+|Page de consultation sécurisée
>|Objectif 3+| Vérifier que la page consultProduit.php n'est pas accessible si l'id du produit n'est pas correctement renseignée

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Accéder à la page sans renseigner l'idProduit ^|Redirection vers la page d'accueil ^|OK
^|2 ^|Accéder à la page avec un idProduit n'étant pas au bon format ^|Redirection vers la page d'accueil ^|OK
^|3 ^|Accéder à la page avec un idProduit n'étant pas dans la base de données ^|Redirection vers la page d'accueil ^|OK
^|4 ^|Accéder à la page avec un idProduit valide ^|Accès à la page ^|OK

|====

|====

>|Cas de test 3+|Test-02-01-02
>|Titre 3+|Ajouter au panier
>|Objectif 3+| Vérifier que le bouton "ajouter au panier" de la page consultProduit.php ajoute le produit au panier correctement lorsqu'on clique dessus

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Le bouton est cliqué ^|Le produit est ajouté au panier ^|OK
^|2 ^|Des cases de choix sont cochées et une quantité séléctionnée ^|Les données séléctionnées sont enregistrées dans le panier lors de l'ajout^|OK
^|4 ^|La quantité est modifiée ^|La quantité sélectionnée ne peut pas dépasser le stock du produit en question ^|OK

|====

|====

>|Cas de test 3+|Test-02-01-03
>|Titre 3+|Traitement des avis
>|Objectif 3+| Vérifier que le bouton "ajouter au panier" de la page consultProduit.php ajoute le produit au panier correctement lorsqu'on clique dessus

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Le bouton est cliqué ^|Le produit est ajouté au panier ^|OK
^|2 ^|Des cases de choix sont cochées et une quantité séléctionnée ^|Les données séléctionnées sont enregistrées dans le panier lors de l'ajout^|OK
^|4 ^|La quantité est modifiée ^|La quantité sélectionnée ne peut pas dépasser le stock du produit en question ^|OK

|====

*TO COMPLETE*
