= Cahier De Recette du site web REVIVE
:toc:
:toc-title: Sommaire

Groupe *G2A-7* : Tilian HURÉ, Vincent MIQEU-DENJEAN, Matéo PÉPIN, Hugo WENDJANEH

{empty} +

== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre de la conception d'un site web pour l'entreprise REVIVE. Ce document spécifie l'ensemble des cas testés pour ce dernier.

{empty} +

== II. Pre-Requis :
[.text-justify]
L'exécution des tests requiert l'accès au site web REVIVE :

* http://193.54.227.164/~SAESYS07/[Adresse externe]
* http://192.168.224.139/~SAESYS07/[Adresse interne]

=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les User-Stories spécifiées dans le *CDCF* donné dans l'appel d'offre de REVIVE.

{empty} +

=== 2. Environnement de test :
[.text-justify]
Un navigateur web quelconque.

{empty} +

== III. Cas de test :
=== 1. Connexion et données de compte :
==== 1.1 Connexion :

|====

>|Cas de test 3+|Test-01-01-01
>|Titre 3+|Connexion en tant que client
>|Objectif 3+| Vérifier qu'il est possible de se connecter en tant que client sur la page connexion.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Saisir une mauvaise adresse mail  ^|Affichage d'un message d'erreur ^|OK
^|2 ^|Saisir un mauvais mot de passe ^|Affichage d'un message d'erreur ^|OK
^|3 ^|Saisir des données de client correctes ^|Connexion en tant que client et redirection vers la page d'accueil ^|OK

|====

|====

>|Cas de test 3+|Test-01-01-02
>|Titre 3+|Connexion en tant qu'administrateur
>|Objectif 3+| Vérifier qu'il est possible de se connecter en tant qu'administrateur sur la page connexion.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Saisir une mauvaise adresse mail  ^|Affichage d'un message d'erreur ^|OK
^|2 ^|Saisir un mauvais mot de passe ^|Affichage d'un message d'erreur ^|OK
^|3 ^|Saisir des données d'administrateur correctes ^|Connexion en tant qu'administrateur et redirection vers la page d'accueil ^|OK

|====

==== 1.2 Création d'un compte :

|====

>|Cas de test 3+|Test-01-02-01
>|Titre 3+|Création d'un compte client
>|Objectif 3+| Vérifier qu'il est possible de créer un compte client sur la page creationCompte.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Saisir une mauvaise adresse mail  ^|Affichage d'un message d'erreur ^|OK
^|2 ^|Saisir un mauvais mot de passe ^|Affichage d'un message d'erreur ^|OK
^|3 ^|Saisir des données de client correctes ^|Ajout des données dans la BD et redirection vers la page de connexion ^|OK

|====

==== 1.3 Consultation d'un compte :

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Page sécurisée
>|Objectif 3+| Vérifier que la page consultCompte.php n'est pas accessible si l'utilisateur n'est pas connecté

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Accéder à la page sans être connecté  ^|Redirection vers la page de connexion ^|OK
^|2 ^|Accéder à la page avec de mauvaises données de session ^|Redirection vers la page de connexion ^|OK
^|3 ^|Accéder à la page en étant connecté en tant que client ou administrateur ^|Accès à la page ^|OK

|====

|====

>|Cas de test 3+|Test-01-03-02
>|Titre 3+|Consultation d'un compte client
>|Objectif 3+| Vérifier qu'il est possible de consulter les données d'un compte client sur la page consultCompte.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Accéder à la page en étant connecté en tant que client ^|Accès à la page et affichage des données du compte client ^|OK

|====

|====

>|Cas de test 3+|Test-01-03-03
>|Titre 3+|Consultation d'un compte administrateur
>|Objectif 3+| Vérifier qu'il est possible de consulter les données d'un compte administrateur sur la page consultCompte.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Accéder à la page en étant connecté en tant qu'administrateur ^|Accès à la page et affichage des données du compte administrateur ^|OK

|====

==== 1.4 Modification d'un compte :

|====

>|Cas de test 3+|Test-01-04-01
>|Titre 3+|Page sécurisée
>|Objectif 3+| Vérifier que la page modifierCompte.php n'est pas accessible si l'utilisateur n'est pas connecté

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Accéder à la page sans être connecté  ^|Redirection vers la page de connexion ^|OK
^|2 ^|Accéder à la page avec de mauvaises données de session ^|Redirection vers la page de connexion ^|OK
^|3 ^|Accéder à la page en étant connecté en tant que client ou administrateur ^|Accès à la page ^|OK

|====

|====

>|Cas de test 3+|Test-01-04-02
>|Titre 3+|Modification d'un compte client
>|Objectif 3+| Vérifier qu'il est possible de modifier les données d'un compte client sur la page modifierCompte.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Saisir une mauvaise adresse mail ou une adresse déjà existante  ^|Affichage d'un message d'erreur ^|OK
^|2 ^|Saisir un mauvais nouveau mot de passe ^|Affichage d'un message d'erreur ^|OK
^|3 ^|Saisir un mauvais ancien mot de passe ^|Affichage d'un message d'erreur ^|OK
^|4 ^|Saisir des données de client correctes ^|Modification des données dans la BD ^|OK

|====

|====

>|Cas de test 3+|Test-01-04-03
>|Titre 3+|Modification d'un compte administrateur
>|Objectif 3+| Vérifier qu'il est possible de modifier les données d'un compte administrateur sur la page modifierCompte.php

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Saisir une mauvaise adresse mail ou une adresse déjà existante  ^|Affichage d'un message d'erreur ^|OK
^|2 ^|Saisir un mauvais nouveau mot de passe ^|Affichage d'un message d'erreur ^|OK
^|3 ^|Saisir un mauvais ancien mot de passe ^|Affichage d'un message d'erreur ^|OK
^|4 ^|Saisir des données de client correctes ^|Modification des données dans la BD ^|OK

|====

{empty} +

=== 2. Pages produit
==== 2.1 Consultation de produit :

|====

>|Cas de test 3+|Test-02-01-01
>|Titre 3+|Page de consultation sécurisée
>|Objectif 3+| Vérifier que la page consultProduit.php n'est pas accessible si l'id du produit n'est pas correctement renseignée

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Accéder à la page sans renseigner l'idProduit ^|Redirection vers la page d'accueil ^|OK
^|2 ^|Accéder à la page avec un idProduit n'étant pas au bon format ^|Redirection vers la page d'accueil ^|OK
^|3 ^|Accéder à la page avec un idProduit n'étant pas dans la base de données ^|Redirection vers la page d'accueil ^|OK
^|4 ^|Accéder à la page avec un idProduit valide ^|Accès à la page ^|OK

|====

|====

>|Cas de test 3+|Test-02-01-02
>|Titre 3+|Ajouter au panier
>|Objectif 3+| Vérifier que le bouton "ajouter au panier" de la page consultProduit.php ajoute le produit au panier correctement lorsqu'on clique dessus

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Le bouton est cliqué ^|Le produit est ajouté au panier ^|OK
^|2 ^|Des cases de choix sont cochées et une quantité séléctionnée ^|Les données séléctionnées sont enregistrées dans le panier lors de l'ajout^|OK
^|3 ^|La quantité est modifiée ^|La quantité sélectionnée ne peut pas dépasser le stock du produit en question ^|OK

|====

|====

>|Cas de test 3+|Test-02-01-03
>|Titre 3+|Traitement des avis
>|Objectif 3+|Un utilisateur peut ajouter des avis sur un produit dans la page de consultation de ce dernier

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|L'utilisateur est sur la page de consultation d'un produit ^|Il voit la liste des avis qui y sont associés ^|OK
^|2 ^|L'utilisateur a sélectionné une intervale de note pour filtrer les avis ^|Les avis correspondant à cette note sont affichés^|OK
^|3 ^|L'utilisateur n'est pas connecté ^|Un bouton intitulé "connectez-vous pour ajouter un avis" apparaît et mène vers la page de connexion ^|OK
^|4 ^|L'utilisateur est connecté ^|Un bouton intitulé "Ajouter un avis" apparaît et mène vers le formulair d'ajout d'un avis ^|OK
^|5 ^|L'utilisateur valide le formulaire d'ajout d'un avis ^|Un avis est ajouté à son nom sur le produit concerné ^|OK

|====

==== 2.2 Listage des produits :

|====

>|Cas de test 3+|Test-02-02-01
>|Titre 3+|Affichage des produits par la barre de recherche
>|Objectif 3+|Un utilisateur peut utiliser la barre de recherche dans le header pour afficher la liste des produits

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|L'utilisateur appuie sur "entrée" ou clique sur la loupe sans rien écrire dans la barre de recherche ^|Tous les produits de la base de données sont affichés ^|OK
^|2 ^|L'utilisateur écrit "Ordinateur" dans la barre de recherche ^|Tous les produits dont le nom ou la description contiennent "ordinateur" apparaissent ^|OK
^|3 ^|L'utilisateur clique sur un produit affiché ^|Il est redirigé vers la page de consultation de ce produit  ^|OK

|====

|====

>|Cas de test 3+|Test-02-02-02
>|Titre 3+|Affichage des produits par le menu déroulant
>|Objectif 3+|Un utilisateur peut utiliser le menu déroulant dans le header pour afficher la liste des produits

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|L'utilisateur clique sur la catégorie "Xiaomi" ^|Tous les produits correspondants à la catégorie "Xiaomi" sont affichés ^|OK
^|2 ^|L'utilisateur clique sur la grande catégorie "Smartphone" ^|Tous les produis de la catégorie "Smartphone" et des sous-catégorires de cette dernière (tel que "Xiaomi) sont affichés ^|OK
^|3 ^|L'utilisateur clique sur un produit affiché ^|Il est redirigé vers la page de consultation de ce produit  ^|OK

|====

==== 2.3 Panier :

|====

>|Cas de test 3+|Test-02-03-01
>|Titre 3+|Affichage du panier (connecté)
>|Objectif 3+|Lorsqu'un utilisateur est connecté, le panier de cet utilisateur est affiché dans la page du panier

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|L'utilisateur accède à la page du panier ^|Les articles qu'il a précédemment ajouté dans son panier sont affichés ^|OK
^|2 ^|L'utilisateur modifie la quantité d'un article ^|La quantité est modifiée dans la base de données et le prix est recalculé en conséquence ^|OK
^|3 ^|L'utilisateur clique sur le bouton pour supprimer un article ^|L'article est supprimé de la BD et n'est plus affiché sur la page ^|OK

|====

|====

>|Cas de test 3+|Test-02-03-02
>|Titre 3+|Affichage du panier (non connecté)
>|Objectif 3+|Lorsqu'un utilisateur n'est pas connecté en tant que client, il lui est affecté un panier à l'aide de cookies

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|L'utilisateur accède à la page du panier ^|Si non existant, un cookie "panier" est créé avec une durée de vie d'une semaine, si existant le panier est affiché avec les articles qu'il a mis dedans ^|OK
^|2 ^|L'utilisateur modifie la quantité d'un article ^|La quantité est modifiée dans le cookie et le prix est recalculé en conséquence ^|OK
^|3 ^|L'utilisateur clique sur le bouton pour supprimer un article ^|L'article est supprimé du cookie et n'est plus affiché sur la page ^|OK

|====

{empty} +

=== 3. Administration du site
==== 3.1 CRUD des produits :

|====

>|Cas de test 3+|Test-03-01-01
>|Titre 3+|Ajouter un produit
>|Objectif 3+|Les administrateurs du serveur peuvent ajouter un produit à la liste

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Essayer d'accéder à la page sans être connecté en tant qu'administrateur ^|Redirection vers la page de connexion ^|OK
^|2 ^|Essayer d'accéder à la page en étant connecté en tant qu'administrateur ^|Accès à la page ^|OK
^|3 ^|Remplir des champs ne correspondant pas aux données à mettre dans la BD ^|Affichage d'une erreur ^|OK
^|4 ^|Remplir tous les champs correctement ^|Affichage d'un message indiquant la réussite de l'ajout et insertion du produit dans la base de données ^|OK

|====

|====

>|Cas de test 3+|Test-03-01-02
>|Titre 3+|Supprimer un produit
>|Objectif 3+|Les administrateurs du serveur peuvent supprimer un produit de la base de données, il n'est jamais vraiment supprimé mais plutôt désactivé.

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Essayer d'accéder à la page sans être connecté en tant qu'administrateur ^|Redirection vers la page de connexion ^|OK
^|2 ^|Essayer d'accéder à la page en étant connecté en tant qu'administrateur ^|Accès à la page ^|OK
^|3 ^|Sélectionner le produit voulu et cliquer sur "supprimer" ^|Affichage d'un message indiquant la réussite de la suppression et désactivation du produit dans la base de données ^|OK

|====

==== 3.2 CRUD des catégories :

|====

>|Cas de test 3+|Test-03-02-01
>|Titre 3+|Ajouter une catégorie
>|Objectif 3+|Les administrateurs du serveur peuvent ajouter des catégories pour y affecter des produits

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Essayer d'accéder à la page sans être connecté en tant qu'administrateur ^|Redirection vers la page de connexion ^|OK
^|2 ^|Essayer d'accéder à la page en étant connecté en tant qu'administrateur ^|Accès à la page ^|OK
^|3 ^|Remplir des champs ne correspondant pas aux données à mettre dans la BD ^|Affichage d'une erreur ^|OK
^|4 ^|Remplir tous les champs correctement ^|Affichage d'un message indiquant la réussite de l'ajout et insertion de la catégorie dans la base de données ^|OK

|====

|====

>|Cas de test 3+|Test-03-02-02
>|Titre 3+|Supprimer une catégorie
>|Objectif 3+|Les administrateurs du serveur peuvent supprimer une catégorie de la base de données. Une catégorie ne peut être supprimée que si elle ne possède plus de catégories filles ni de produits assignés.

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Essayer d'accéder à la page sans être connecté en tant qu'administrateur ^|Redirection vers la page de connexion ^|OK
^|2 ^|Essayer d'accéder à la page en étant connecté en tant qu'administrateur ^|Accès à la page ^|OK
^|3 ^|Sélectionner la catégorie voulue et cliquer sur "supprimer" ^|Affichage d'un message indiquant la réussite de la suppression et suppression ed la catégorie et des produits concernés dans la base de données ^|OK

|====